---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  user: ubuntu

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/ssh_keys/aws.pem"
  vars_files:
    - /etc/ansible/group_vars/private.yml

  roles:
    - ec2-provision 

  hosts: localhost
  become: no
  gather_facts: no
